#include ".\helping_functions.pwn"
#include ".\server_config\__server_config.pwn"
#include ".\classes.pwn"
#include ".\dialogs.pwn"
#include ".\player_variables.pwn"
#include ".\authentication\__authentication.pwn"
